url:
    # hostname: dig prod-live-front.playbattlegrounds.com
    hostname: d194krux5qtmmq.cloudfront.net
    protocol: https
    index: index.html

websocket:
    ssl:
        # url: dig prod-live-entry.playbattlegrounds.com
        # url: wss://prod-live-entry.playbattlegrounds.com/userproxy?provider=steam&ticket={ticket}&playerNetId={playerNetId}&cc={countryCode}&clientGameVersion={clientGameVersion}
        url: wss://prod-live-main-userproxy-413930521.us-east-1.elb.amazonaws.com/userproxy

server:
    # Override with `--debug=False`
    debug: true

    # Override with `--port=80`
    port: 3001

    # Folder path for optional js and css files to embed
    assets:
        base: "assets"
        embedded: "assets/embedded"
    
    # SSL certificates (optional, only needed if passing --ssl)
    ssl:
        certificate: certs/generated/cert.pem
        private_key: certs/generated/cert-no-password.key